### ISSUE TITLE
USER STORY: Get feedback

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/what-is-cooking#10]
As a **Site User** I can **get corresponding feedback after taking an action** so that **I know whether my actions were successfully run or not**

**Acceptance Criteria**:
- Information about whether the user's actions were successful or not should be displayed.

**Tasks**:

- [x] Add Bootstrap alert messages into base.html.
- [x] Add message tags into settings.py.
- [x] Create a timeout function for alert messages.
