### ISSUE TITLE
USER STORY: Like/unlike 

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/what-is-cooking#13]
As a **logged-in User** I can **like/unlike others' recipes** so that **I can interact with the content**

**Acceptance Criteria**:
- The option (icon) should appear in the detailed recipe view. 
- The option should be accessible only to logged-in users.
- If a user hasn't liked a recipe before, their like should be added to the total count.
- If a user had previously liked a recipe and then likes it again, their like should be removed from the total count.

**Tasks**:

- [x] Create a view code to check if the recipe was liked before and adjust the like count accordingly.
- [x] Update the "recipe_detail" template to include a "like" icon below each recipe.
- [x] Use {% if user.is_authenticated %}.
- [x] Add a method to count likes.
- [x] Add a URL path.
