### ISSUE TITLE
USER STORY: Comment on recipes

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/what-is-cooking#14]
As a **logged-in User** I can **leave comments on recipes** so that **I can share my opinion/ask questions**

**Acceptance Criteria**:
- Comment field should be visible only for logged-in users.
- The option should be placed below the recipe details.
- Admin should approve comments before they are displayed on the page.
- Users should receive feedback when they send a comment.

**Tasks**:

- [x] Create CommentForm class.
- [x] Create the view code.
- [x] Update "recipe_detail" page to display form for logged-in users (use {% if user.is_authenticated %}).
- [x] Add an alert message to be displayed after each comment has been sent.
- [x] Test completted functionality.
