### ISSUE TITLE
USER STORY: Check/approve comments

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/what-is-cooking#15]
As a **Site Admin** I can **view, approve, and delete comments** so that **I can remove any inappropriate content**

**Acceptance Criteria**:
- The admin has the ability to review user comments before they are displayed on the website.

**Tasks**:

- [x]  Create a Comment model.
- [x]  Check that the value of "approved" is set to False.
- [x]  Log in to the admin site to check whether everything is working.
