### ISSUE TITLE
USER STORY: View comments

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/what-is-cooking#16]
As a **Site User** I can **view comments on an individual post** so that **I can read the conversation**

**Acceptance Criteria**:
- Users of the site can view all comments that have been previously approved on a specific post.
- If there are no comments yet, the user should receive the information about that.

**Tasks**:

- [x] Set "approved" in the Comment Model to False.
- [x] Log in to the admin site and approve comments that should be posted.
- [x] Loop through the comments and display them to the user by using the "recipe_detail" template.
