### ISSUE TITLE
USER STORY: Create/publish recipe

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/what-is-cooking#17]
As a **logged-in User** I can **create/publish recipes** so that **I can share something I find delicious with others**

**Acceptance Criteria**:
- The "Add Recipe" link should be placed in the navigation bar to be visible and easily accessible.
- It should be displayed only for logged-in users.
- The user should be directed to a recipe form page when clicking the link.
- Once the form is submitted, the user should receive appropriate feedback in response.

**Tasks**:

- [x] Install crispy-forms.
- [x] Create "add_recipe" template.
- [x] Import forms and create form_fields.
- [x] Create a URL pattern to be able to render the template.
- [x] Create the view code.
- [x] Test the completed functionality.
