### ISSUE TITLE
USER STORY: Delete recipes

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/what-is-cooking#19]
As a **logged-in User** I can **delete my recipes** so that **they are no longer published on the site**

**Acceptance Criteria**:
- An "delete" button should only be visible to the user who posted the recipe.
- The user should be prompted with a confirmation question before the deletion process.
- A confirmation message should be provided for the user after clicking the "delete" button.
- The user should be redirected to the "recipes" page when choosing to delete.
- The user should be redirected to the detailed page if they choose not to delete.

**Tasks**:
- [x]  Create a "delete" template.
- [x]  Put the "delete" button within the if-statement checking whether the user is the recipe's author.
- [x] Create a URL path.
- [x] Create the view code.
- [x]  Add a message to the user.
- [x] Test the completed functionality.
