### ISSUE TITLE
USER STORY: Account registration

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/what-is-cooking#2]
As a **Site User** I can **register an account** so that **I can access publishing, commenting, and liking features**

**Acceptance Criteria**:
  - The option should appear on the navigation bar in order to be visible and easily accessible.
  - The user should be able to register by filling in a name, email, and password and confirming the password.
  - Once the signup form is completed, the user is registered and logged in.
  - After creating an account the corresponding feedback should be provided for the user.

**Tasks**:

- [x] Install Django Allauth.
- [x] Customize the signup page.
- [x] Test the completed functionality.
