### ISSUE TITLE
USER STORY: Read recipes

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/what-is-cooking#20]
As a **Site user** I can **read published recipes** so that **I can get some inspiration**

**Acceptance Criteria**:
- The "Recipes" link should be on the navigation bar in order to be visible and easily accessible.
- All the users should be able to see all the published recipes.
- The user should be able to view detailed recipe information by clicking on each recipe.

**Tasks**:

- [x] Create "recipes" and "recipe_detail" templates.
- [x] Create views and URL patterns.
- [x] Add a recipe on the admin site to test functionality.
