### ISSUE TITLE
USER STORY: Get estimated time

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/what-is-cooking#21]
As a **Site User** I can **easily see the approximate required time to prepare each meal** so that **I can choose recipes and allocate my time accordingly**

**Acceptance Criteria**:
- The estimated time should be seen on the recipe page without having to go to the detailed page.

**Tasks**: 
- [x] Put estimated_time into the database. 
- [x] Put the estimated_time field in the form so the blog's users fill it out when posting recipes.
- [x] Display it in the recipe template.
