### ISSUE TITLE
USER STORY: Navigate

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/what-is-cooking#22]
As a **Site User** I can **find navigation links at the top** so that **I easily can navigate the site**

**Acceptance Criteria**:
- The navigation bar must be placed at the top of the page.
- It must be responsive on different devices.
- It is important for links to have easily understandable names.
- By clicking on the title the user should be redirected to the home page every time.

**Tasks**:

- [x] Use bootstrap nav element with hamburger drop-down.
- [x] Give the links easily understandable names.
- [x] Add custom CSS.
- [x] Test the completed functionality.
