### ISSUE TITLE
USER STORY: Sign in with username/password

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/what-is-cooking#3]
As a **Site User** I can **sign in with my username and password** so that **I can share my recipes and like/comment on others'**

**Acceptance Criteria**:
-  The option should appear on the navigation bar in order to be visible and easily accessible.
 - The login feature enables users to access their accounts and utilize all functions available on the site.
 - Navbar links should change to Logout instead of Sign Up and Login.
 - After logging in the corresponding feedback should be provided for the user.

**Tasks**:

- [x]  Utilise previously installed Django Allauth.
- [x]  Customize the log-in page.
- [x]  Test the completed functionality.
