### ISSUE TITLE
USER STORY: Log out

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/what-is-cooking#5]
As a **logged-in user** I can **easily log out** so that **I can avoid somebody else accessing my account**

**Acceptance Criteria**:
- The option should appear on the navigation bar in order to be visible and easily accessible.
- When the user clicks the logout button, a question of whether the user is sure should appear.
- A confirmation message should be provided for the user.
- Navbar links change to Sign Up and Login instead of Logout

**Task**:

- [x]  Utilise previously installed Django Allauth.
- [x]  Customize the log-out page.
- [x]  Test the completed functionality.
