### ISSUE TITLE
USER STORY: Social media links

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/what-is-cooking#7]
As a **Site User** I can **click on links to the site's social media** so that **I can explore more of its content and context**

**Acceptance Criteria**:
-  Social media links are displayed in the footer of the page.
- Icons are used instead of social media titles.
- The links should be opened in separate tabs.

**Tasks**:

- [x] Create a footer in the base template using Font Awesome icons.
- [x] Add custom CSS for styling.
- [x] Add "target=_blank" to make the links open in a separate tag.
