### ISSUE TITLE
USER STORY: Choose between categories

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/what-is-cooking#9]
As a **Site User** I can **choose between different categories** so that **I can decide what I would like to prepare and when**

**Acceptance Criteria**:
- The various categories should be easily visible on the homepage.
- The user should be able to click on each category and be directed to the page with recipes in that category.
- If there are no recipes in the selected category, the user should get the information about that.

**Tasks**:

- [x]  Create a "category" template.
- [x]  Create a URL path.
- [x]  Create the view code.
- [x] Wire up the category boxes in the index.html.
- [x] Use {% empty %} to tell the user if there are no recipes in the selected category.
